apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: auto-dba
  name: clusterdatabaseservers.autodba.sircremefresh.dev
spec:
  group: autodba.sircremefresh.dev
  names:
    kind: ClusterDatabaseServer
    listKind: ClusterDatabaseServerList
    plural: clusterdatabaseservers
    singular: clusterdatabaseserver
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: "A ClusterDatabaseServer"
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Desired state of the ClusterDatabaseServer resource.
              properties:
                authSecretRef:
                  description: 'The reference to the secret holding the authentication credentials'
                  properties:
                    name:
                      description: 'Name of the resource being referred to. More
                                    info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                      type: string
                      pattern: '^[a-z0-9-]{3,63}$'
                  required:
                    - name
                  type: object
                host:
                  description: 'The Host of the database server to connect to'
                  type: string
                port:
                  description: 'The Port of the database server to connect to'
                  type: string
                databaseType:
                  description: 'Database type connecting to'
                  enum:
                    - PostgreSQL
                  type: string
              required:
                - authSecretRef
                - host
                - port
                - databaseType
              type: object
            status:
              description: Status of the ClusterDatabaseServer. This is set and managed automatically.
              properties:
                status:
                  description: Status of the condition, one of (`True`, `False`,
                    `Unknown`).
                  enum:
                    - "True"
                    - "False"
                    - Unknown
                  type: string
                type:
                  description: Type of the condition, known values are (`Ready`).
                  type: string
              required:
                - status
                - type
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
