apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app: auto-dba
  name: databases.autodba.sircremefresh.dev
  namespace: auto-dba-dev
spec:
  group: autodba.sircremefresh.dev
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
  scope: Namespaced
  versions:
    - name: v1alpha1
      additionalPrinterColumns:
        - jsonPath: .spec.serverRef.name
          name: DatabaseServer
          type: string
        - jsonPath: .status.status
          name: Status
          type: string
      schema:
        openAPIV3Schema:
          description: "A Database"
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: Desired state of the Certificate resource.
              properties:
                secretName:
                  description: SecretName is the name of the secret resource that will
                    be automatically created and managed by this Certificate resource.
                    It will be populated with a private key and certificate, signed
                    by the denoted issuer.
                  type: string
                  pattern: '^[a-z0-9-]{3,63}$'
                serverRef:
                  description: SecretName is the name of the secret resource that will
                    be automatically created and managed by this Certificate resource.
                    It will be populated with a private key and certificate, signed
                    by the denoted issuer.
                  properties:
                    name:
                      description: ''
                      type: string
                      pattern: '^[a-z0-9-]{3,63}$'
                  required:
                    - name
                  type: object
              required:
                - secretName
                - serverRef
              type: object
            status:
              description: Status of the Database. This is set and managed automatically.
              properties:
                status:
                  description: Status of the condition, one of (`True`, `False`,
                    `Unknown`).
                  enum:
                    - "True"
                    - "False"
                    - Unknown
                  type: string
                type:
                  description: Type of the condition, known values are (`Ready`).
                  type: string
              required:
                - status
                - type
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: { }
